name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Run make
      run:  sudo apt update && sudo apt install -y clang make make

    - name: make test_match
      run: sudo apt update && sudo apt install -y flex && make test_match
